### ISSUE TITLE
Have a macro dashboard of orders per state

### ISSUE THREAD

**Issue by devteamshippeo** [shippeo/monitoring#15]
## General description
In order to spot outage and understand causes of outages, we want to be able to know :

* Number of orders potentially active
* Number of orders paired
* Number of orders active
* _﹍Number of orders with a recent position﹍_
* ﹍_Number of orders with a recent ETA_﹍

## Users stories
* [✓ #3731 ⁃ [Active orders] Monitor active orders for various usages](https://app.asana.com/0/0/1132549904321746/f/)

## Acceptance criteria
* [ ]

**Comment by dcalliste** [comment]
@bricehua l'idée était de faire ça avec Tableau (repo /data) non ? Ou tu souhaites que l'on regarde si réalisable dans Grafana ?

**Comment by bricehua** [comment]
On va d'abord regarder avec la team Orders Management !

Brice Hua
VP Product & Co-founder
[image: Shippeo] <http://shippeo.com/>
+33 6 66 12 89 85
brice.hua@shippeo.com
[image: Linkedin] <https://fr.linkedin.com/company/shippeo>[image: Shippeo]
<https://twitter.com/shippeofra>
