### ISSUE TITLE
Update library to monitor request responses

### ISSUE THREAD

**Issue by dcalliste** [shippeo/monitoring#4]
## General description
Update the SF library to monitor request responses by status, time and memory.

## Users stories ##
As a product team member I want to monitor request responses by status, time and memory so that I can identify issues and have performance indicators

Count status, time and memory for each request on API

## Acceptance criteria ##

Check status, time and memory is count for all request on API, and ability to filter on request type and datime

**Comment by babaorum** [comment]
we want to monitor number of requests (counter), time spent, cpu usage, memory usage, and if possible time spent by the database.

**Comment by dcalliste** [comment]
Conforme
